services:
  gateway-api:
    build:
      context: ./gateway_service/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure

  temperature-api:
    build:
      context: .
      dockerfile: temperature_service/Dockerfile
    ports:
      - "8081:8081"
    restart: on-failure

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    restart: always
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
